#!/usr/bin/env ruby
# frozen_string_literal: true

def human_duration(duration_in_seconds)
  n = duration_in_seconds.round
  parts = []
  [60, 60, 24].each{|d| n, r = n.divmod d; parts << r; break if n.zero?}
  parts << n unless n.zero?
  pairs = parts.reverse.zip(%w(d h m s)[-parts.size..-1])

  r = []
  r << pairs.shift
  r << pairs.shift if pairs[0] && pairs[0][0] > 0

  r.flatten.join
end

puts human_duration(ARGV[0].to_i)
